# Generated by Django 3.2.20 on 2023-09-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230928_0350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='products',
        ),
    ]
