# Generated by Django 3.2.20 on 2023-09-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230928_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
