# Generated by Django 3.2.20 on 2023-09-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_stock_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
