# Generated by Django 3.2.20 on 2023-09-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
